AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple Hello Lambda function

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambda_handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 3
      Events:
        HelloApi:
          Type: Api
          Properties:
            Path: /hello
            Method: GET